mutation AddShift($employee_id: Int!, $time_in: timestamptz!) {
  insert_Shift(objects: { employee_id_fk: $employee_id, time_in: $time_in }) {
    returning {
      time_in
      id
      time_out
      employee_id_fk
    }
    affected_rows
  }
}
